# Site settings
title: Escape Excel
tag_text: Escape Excel
description: a tool for preventing gene symbol and accession conversion errors

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
